apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "nerServer.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8000
    targetPort: http
  selector: {{ include "nerServer.selectorLabels" . | nindent 4 }}
